server:
  port: 8010
spring:
  application:
    name: feign-demo
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
logging:
  level:
      com.kmmshmily.feigndemo.HelloService: debug
